# Generated by Django 2.2 on 2021-07-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60, verbose_name='Введите прилагательное')),
            ],
            options={
                'verbose_name': 'Прилагательное',
                'verbose_name_plural': 'Прилагательные',
            },
        ),
    ]
